### ISSUE TITLE
pysander built for `osx-64` in `osx-arm64` packages

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/ambertools-feedstock#156]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

```shell
$ micromamba create --name ambertools-test ambertools -c conda-forge -yq
warning  libmamba 'root_prefix' set with default value: /Users/mattthompson/micromamba
warning  libmamba [tk-8.6.13-h5083fa2_1] The following files were already present in the environment:
    - include/X11/DECkeysym.h
    - include/X11/HPkeysym.h
    - include/X11/Sunkeysym.h
    - include/X11/X.h
    - include/X11/XF86keysym.h
    - include/X11/Xatom.h
    - include/X11/Xfuncproto.h
    - include/X11/ap_keysym.h
    - include/X11/keysym.h
    - include/X11/keysymdef.h
warning  libmamba [xorg-libx11-1.8.10-h2321a68_0] The following files were already present in the environment:
    - include/X11/Xlib.h
    - include/X11/Xutil.h
    - include/X11/cursorfont.h
[~]
$ micromamba activate ambertools-test                                  9:02:01
warning  libmamba 'root_prefix' set with default value: /Users/mattthompson/micromamba
(ambertools-test) [~]
$ python -c "import sander"                                            9:02:10
Could not import the compiled Python-sander interface. Make sure you have the Python development libraries installed and that you have sourced amber.sh or amber.cshTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mattthompson/micromamba/envs/ambertools-test/lib/python3.12/site-packages/sander/__init__.py", line 14, in <module>
    from . import pysander as _pys
ImportError: dlopen(/Users/mattthompson/micromamba/envs/ambertools-test/lib/python3.12/site-packages/sander/pysander.cpython-312-darwin.so, 0x0002): tried: '/Users/mattthompson/micromamba/envs/ambertools-test/lib/python3.12/site-packages/sander/pysander.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/mattthompson/micromamba/envs/ambertools-test/lib/python3.12/site-packages/sander/pysander.cpython-312-darwin.so' (no such file), '/Users/mattthompson/micromamba/envs/ambertools-test/lib/python3.12/site-packages/sander/pysander.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64'))
```

This works fine if forcing everything to Intel architecture with `CONDA_SUBDIR=osx-64`:
```shell
$ CONDA_SUBDIR=osx-64 micromamba create --name ambertools-test ambertools -c conda-forge -yq
warning  libmamba 'root_prefix' set with default value: /Users/mattthompson/micromamba
warning  libmamba Extracted package cache '/Users/mattthompson/micromamba/pkgs/python_abi-3.12-5_cp312' has invalid size
warning  libmamba Extracted package cache '/Users/mattthompson/micromamba/pkgs/python_abi-3.12-5_cp312' has invalid SHA-256 checksum
warning  libmamba Package tarball '/Users/mattthompson/micromamba/pkgs/python_abi-3.12-5_cp312.conda' is invalid
warning  libmamba [tk-8.6.13-h1abcd95_1] The following files were already present in the environment:
    - include/X11/DECkeysym.h
    - include/X11/HPkeysym.h
    - include/X11/Sunkeysym.h
    - include/X11/X.h
    - include/X11/XF86keysym.h
    - include/X11/Xatom.h
    - include/X11/Xfuncproto.h
    - include/X11/ap_keysym.h
    - include/X11/keysym.h
    - include/X11/keysymdef.h
warning  libmamba [xorg-libx11-1.8.10-ha6c16c8_0] The following files were already present in the environment:
    - include/X11/Xlib.h
    - include/X11/Xutil.h
    - include/X11/cursorfont.h
warning  libmamba 'root_prefix' set with default value: /Users/mattthompson/micromamba
(ambertools-test) [~]
$ micromamba activate ambertools-test
warning  libmamba 'root_prefix' set with default value: /Users/mattthompson/micromamba
(ambertools-test) [~]
$ python -c "import sander"
```

### Installed packages

```shell
List of packages in environment: "/Users/mattthompson/micromamba/envs/ambertools-test"

  Name             Version       Build                              Channel    
─────────────────────────────────────────────────────────────────────────────────
  ambertools       23.6          cuda_None_nompi_py312hc98840c_105  conda-forge
  arpack           3.9.1         nompi_h593882a_101                 conda-forge
  blosc            1.21.6        h5499902_0                         conda-forge
  brotli           1.1.0         hd74edd7_2                         conda-forge
  brotli-bin       1.1.0         hd74edd7_2                         conda-forge
  bzip2            1.0.8         h99b78c6_7                         conda-forge
  c-ares           1.34.3        h5505292_1                         conda-forge
  ca-certificates  2024.8.30     hf0a4a13_0                         conda-forge
  certifi          2024.8.30     pyhd8ed1ab_0                       conda-forge
  contourpy        1.3.1         py312hb23fbb9_0                    conda-forge
  cycler           0.12.1        pyhd8ed1ab_0                       conda-forge
  fftw             3.3.10        nompi_h6637ab6_110                 conda-forge
  fonttools        4.55.0        py312h998013c_0                    conda-forge
  freetype         2.12.1        hadb7bae_2                         conda-forge
  hdf4             4.2.15        h2ee6834_7                         conda-forge
  hdf5             1.14.4        nompi_ha698983_103                 conda-forge
  icu              75.1          hfee45f7_0                         conda-forge
  joblib           1.4.2         pyhd8ed1ab_0                       conda-forge
  kiwisolver       1.4.7         py312h6142ec9_0                    conda-forge
  krb5             1.21.3        h237132a_0                         conda-forge
  lcms2            2.16          ha0e7c42_0                         conda-forge
  lerc             4.0.0         h9a09cb3_0                         conda-forge
  libaec           1.1.3         hebf3989_0                         conda-forge
  libblas          3.9.0         25_osxarm64_openblas               conda-forge
  libboost         1.84.0        h29978a0_6                         conda-forge
  libbrotlicommon  1.1.0         hd74edd7_2                         conda-forge
  libbrotlidec     1.1.0         hd74edd7_2                         conda-forge
  libbrotlienc     1.1.0         hd74edd7_2                         conda-forge
  libcblas         3.9.0         25_osxarm64_openblas               conda-forge
  libcurl          8.10.1        h13a7ad3_0                         conda-forge
  libcxx           19.1.4        ha82da77_0                         conda-forge
  libdeflate       1.22          hd74edd7_0                         conda-forge
  libedit          3.1.20191231  hc8eb9b7_2                         conda-forge
  libev            4.33          h93a5062_2                         conda-forge
  libexpat         2.6.4         h286801f_0                         conda-forge
  libffi           3.4.2         h3422bc3_5                         conda-forge
  libgfortran      5.0.0         13_2_0_hd922786_3                  conda-forge
  libgfortran5     13.2.0        hf226fd6_3                         conda-forge
  libiconv         1.17          h0d3ecfb_2                         conda-forge
  libjpeg-turbo    3.0.0         hb547adb_1                         conda-forge
  liblapack        3.9.0         25_osxarm64_openblas               conda-forge
  libnetcdf        4.9.2         nompi_h853a48d_115                 conda-forge
  libnghttp2       1.64.0        h6d7220d_0                         conda-forge
  libopenblas      0.3.28        openmp_hf332438_1                  conda-forge
  libpng           1.6.44        hc14010f_0                         conda-forge
  libsqlite        3.47.0        hbaaea75_1                         conda-forge
  libssh2          1.11.1        h9cc3647_0                         conda-forge
  libtiff          4.7.0         hfce79cd_1                         conda-forge
  libwebp-base     1.4.0         h93a5062_0                         conda-forge
  libxcb           1.17.0        hdb1d25a_0                         conda-forge
  libxml2          2.13.5        hbbdcc80_0                         conda-forge
  libzip           1.11.2        h1336266_0                         conda-forge
  libzlib          1.3.1         h8359307_2                         conda-forge
  llvm-openmp      19.1.4        hdb05f8b_0                         conda-forge
  lz4-c            1.9.4         hb7217d7_0                         conda-forge
  matplotlib-base  3.9.2         py312h9bd0bc6_2                    conda-forge
  munkres          1.1.4         pyh9f0ad1d_0                       conda-forge
  ncurses          6.5           h7bae524_1                         conda-forge
  netcdf-fortran   4.6.1         nompi_h861be74_107                 conda-forge
  numpy            1.26.4        py312h8442bc7_0                    conda-forge
  openjpeg         2.5.2         h9f1df11_0                         conda-forge
  openssl          3.4.0         h39f12f2_0                         conda-forge
  packaging        24.2          pyhff2d567_1                       conda-forge
  pandas           2.2.3         py312hcd31e36_1                    conda-forge
  parmed           4.3.0         py312hc49f365_0                    conda-forge
  perl             5.32.1        7_h4614cfb_perl5                   conda-forge
  pillow           11.0.0        py312haf37ca6_0                    conda-forge
  pip              24.3.1        pyh8b19718_0                       conda-forge
  pthread-stubs    0.4           hd74edd7_1002                      conda-forge
  pyparsing        3.2.0         pyhd8ed1ab_1                       conda-forge
  python           3.12.7        h739c21a_0_cpython                 conda-forge
  python-dateutil  2.9.0.post0   pyhff2d567_0                       conda-forge
  python-tzdata    2024.2        pyhd8ed1ab_0                       conda-forge
  python_abi       3.12          5_cp312                            conda-forge
  pytz             2024.1        pyhd8ed1ab_0                       conda-forge
  qhull            2020.2        h420ef59_5                         conda-forge
  readline         8.2           h92ec313_1                         conda-forge
  scipy            1.14.1        py312h20deb59_1                    conda-forge
  setuptools       75.6.0        pyhff2d567_0                       conda-forge
  six              1.16.0        pyh6c4a22f_0                       conda-forge
  snappy           1.2.1         hd02b534_0                         conda-forge
  tk               8.6.13        h5083fa2_1                         conda-forge
  tzdata           2024b         hc8b5060_0                         conda-forge
  unicodedata2     15.1.0        py312h0bf5046_1                    conda-forge
  wheel            0.45.1        pyhd8ed1ab_0                       conda-forge
  xorg-libice      1.1.1         hd74edd7_1                         conda-forge
  xorg-libsm       1.2.4         hd74edd7_1                         conda-forge
  xorg-libx11      1.8.10        h2321a68_0                         conda-forge
  xorg-libxau      1.0.11        hd74edd7_1                         conda-forge
  xorg-libxdmcp    1.1.5         hd74edd7_0                         conda-forge
  xorg-libxext     1.3.6         hd74edd7_0                         conda-forge
  xorg-libxt       1.3.1         h5505292_0                         conda-forge
  xorg-xorgproto   2024.1        hd74edd7_1                         conda-forge
  xz               5.2.6         h57fd34a_0                         conda-forge
  zlib             1.3.1         h8359307_2                         conda-forge
  zstd             1.5.6         hb46c0d2_0                         conda-forge
```

### Environment info

```shell
libmamba version : 1.5.10
     micromamba version : 1.5.10
           curl version : libcurl/8.7.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.62.0
     libarchive version : libarchive 3.7.7 zlib/1.2.12 liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6
       envs directories : /Users/mattthompson/micromamba/envs
          package cache : /Users/mattthompson/micromamba/pkgs
                          /Users/mattthompson/.mamba/pkgs
            environment : ambertools-test (active)
           env location : /Users/mattthompson/micromamba/envs/ambertools-test
      user config files : /Users/mattthompson/.mambarc
 populated config files : /Users/mattthompson/.mambarc
                          /Users/mattthompson/.condarc
       virtual packages : __unix=0=0
                          __osx=15.0.1=0
                          __archspec=1=arm64
               channels : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/nodefaults/osx-arm64
                          https://conda.anaconda.org/nodefaults/noarch
       base environment : /Users/mattthompson/micromamba
               platform : osx-arm64
```

**Comment by mikemhenry** [comment]
This is fixed in the rebuild of ambertools 23 and in the new ambertools 24 package
